#! /bin/sh

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] ; then
	buffer=$(tempfile)
	for i in ctags etags ; do
		update-alternatives --display $i > "$buffer" || true
		if ! grep -q '\(exuberant|/usr/man\)' "$buffer" ; then
			update-alternatives --install /usr/bin/$i $i /usr/bin/ctags-exuberant 30 \
				--slave /usr/share/man/man1/$i.1.gz $i.1.gz /usr/share/man/man1/ctags-exuberant.1.gz
		fi
	done
	rm -f "$buffer"
fi

#DEBHELPER#

exit 0
