#! /bin/sh

set -e

if [ "$1" != "upgrade" ] && [ "$1" != "remove" ]; then
	exit 0
fi

if [ "$1" = "remove" ] ; then
	for i in ctags etags ; do
		update-alternatives --remove $i /usr/bin/ctags-exuberant
	done
fi

#DEBHELPER#

exit 0
